#!/bin/sh
set -e

# Stop the service before removal
if [ "$1" = "remove" ]; then
    if [ -d /run/systemd/system ]; then
        systemctl --no-reload stop snapraidd.service 'snapraidd@*.service' >/dev/null || true
    fi
fi

exit 0
