#!/bin/sh
set -e

# Stop and disable the services before removal
if [ "$1" = "remove" ]; then
    if [ -d /run/systemd/system ]; then
        systemctl --no-reload stop snapraidd.service 'snapraidd@*.service' >/dev/null || true
        systemctl --no-reload disable snapraidd.service snapraidd@.service >/dev/null || true
    fi
fi

exit 0
