name: Build
permissions:
  contents: read

on:
  push:
    branches: [ "master", "stable" ]
  pull_request:
    branches: [ "master", "stable" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Validate OpenAPI definition
      run: npx -y @redocly/cli lint --config=.redocly.yaml --max-problems=0 snapraidd.yaml
    - name: Lint YAML with yamllint (strict)
      run: |
        pip install yamllint
        yamllint --strict -c .yamllint.yml snapraidd.yaml
    - run: autoreconf -i
    - run: ./configure
    - run: make distcheck
  build-win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v5
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc autoconf automake make zip
      - run: autoreconf -i
      - run: ./configure --enable-warning-as-error
      - run: make all dist check

